compiler = g++

all: miniproject_main.cpp 
	@echo all
	$(compiler) miniproject_main.cpp miniproject_cell.cpp miniproject_grid.cpp miniproject_BF.cpp mini_def.h -I. -o miniproject 


clean: 
	@echo Cleaning...
	rm -rf *.o *.so *.a *.out